### ISSUE TITLE
Handling errors

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool-binding#12]
How can I catch errors that occur when using `graphcool-binding`? I want to 

* await the resolver call
* inspect it, to see if it has errors
* in case of an error, apply some kind of logic that depends on the specific error. Here I could use the specific error code, or some other information to decide what I do. I could try it again with different input values, return a human readable error, or send an email.

When an error happens currently, it is directly returned to the end-user.

---

Now follows a description to easily enforce an error:

Adjust the `writePost` mutation from` typescript-basic` (see https://github.com/graphql-cli/graphql-boilerplate/tree/master/typescript-basic) to:

```diff
  async writePost(parent, { title, text }, ctx: Context, info) {
    const authorId = getUserId(ctx)
    return ctx.db.mutation.createPost(
      {
        data: {
          title,
          text,
-         isPublished: true,
+         isPublishe: true,
          author: {
            connect: { id: authorId },
          },
        },
      },
      info,
    )
  },
```

Now, running

```graphql
mutation a {
  writePost(
    title: "Nilan"
    text: "Test"
  ) {
    id
  }
}
```

results in 

```graphql
{
  "data": null,
  "errors": [
    {
      "message": "Variable \"$_data\" got invalid value {\"title\":\"Nilan\",\"text\":\"Test\",\"isPublishe\":true,\"author\":{\"connect\":{\"id\":\"cjb9m533i001c01787c2zyhqg\"}}}.\nIn field \"isPublishe\": Unknown field.\nIn field \"isPublished\": Expected \"Boolean!\", found null.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "writePost"
      ]
    }
  ]
}
```

and the server prints

```sh
GraphQLError: Variable "$_data" got invalid value {"title":"Nilan","text":"Test","isPublishe":true,"author":{"connect":{"id":"cjb9m533i001c01787c2zyhqg"}}}.
In field "isPublishe": Unknown field.
In field "isPublished": Expected "Boolean!", found null.
    at Object.locatedError (/Users/marktani/projects/playground/permissions-binding/node_modules/graphql/error/locatedError.js:23:10)
    at Object.checkResultAndHandleErrors (/Users/marktani/projects/playground/permissions-binding/node_modules/graphql-tools/src/stitching/errors.ts:83:11)
    at Object.<anonymous> (/Users/marktani/projects/playground/permissions-binding/node_modules/graphql-tools/src/stitching/delegateToSchema.ts:91:14)
    at step (/Users/marktani/projects/playground/permissions-binding/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:40:23)
    at Object.next (/Users/marktani/projects/playground/permissions-binding/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:21:53)
    at fulfilled (/Users/marktani/projects/playground/permissions-binding/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:12:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Comment by kbrandwijk** [comment]
Wouldn't that just be something like:
```
let result
try {
   result = await ctx.db.mutation.createPost(...)
} catch (error) {
   // do something
}
```

**Comment by marktani** [comment]
You're right, thanks! 👍
