### ISSUE TITLE
Improve error message when calling mutation that doesn't exist

### ISSUE THREAD

**Issue by sorenbs** [graphcool/graphcool-binding#13]
When calling a misspelled mutation like this:

```
ctx.db.mutation.updadteWorkspaceInvitation( [...] )
```

The following (unhelpful) error is returned:

```
TypeError: Cannot read property 'args' of undefined
    at processRootField (/Users/sorenbs/code/gc/cloud/node_modules/graphql-tools/src/stitching/delegateToSchema.ts:202:37)
    at /Users/sorenbs/code/gc/cloud/node_modules/graphql-tools/src/stitching/delegateToSchema.ts:127:15
    at Array.map (<anonymous>)
    at createDocument (/Users/sorenbs/code/gc/cloud/node_modules/graphql-tools/src/stitching/delegateToSchema.ts:125:28)
    at Object.<anonymous> (/Users/sorenbs/code/gc/cloud/node_modules/graphql-tools/src/stitching/delegateToSchema.ts:51:38)
    at step (/Users/sorenbs/code/gc/cloud/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:40:23)
    at Object.next (/Users/sorenbs/code/gc/cloud/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:21:53)
    at /Users/sorenbs/code/gc/cloud/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:15:71
    at Promise (<anonymous>)
    at __awaiter (/Users/sorenbs/code/gc/cloud/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:11:12)
    at Object.delegateToSchema (/Users/sorenbs/code/gc/cloud/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:49:12)
    at Proxy.<anonymous> (/Users/sorenbs/code/gc/cloud/node_modules/graphcool-binding/src/index.ts:169:14)
    at /Users/sorenbs/code/gc/cloud/src/resolvers/Mutation/workspace.ts:96:27
    at step (/Users/sorenbs/code/gc/cloud/src/resolvers/Mutation/workspace.ts:32:23)
    at Object.next (/Users/sorenbs/code/gc/cloud/src/resolvers/Mutation/workspace.ts:13:53)
    at fulfilled (/Users/sorenbs/code/gc/cloud/src/resolvers/Mutation/workspace.ts:4:58)
```

**Comment by kbrandwijk** [comment]
For reference, I have included that here, let's include that in `graphql-binding`: https://github.com/supergraphql/supergraph-orm/blob/master/src/utils.ts#L53-L55

**Comment by schickling** [comment]
Issue moved to [graphcool/graphql-binding #1](https://github.com/graphcool/graphql-binding/issues/1) via [**ZenHub**](https://www.zenhub.com/)
