### ISSUE TITLE
Better logging/debugging

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool-binding#17]
For example, sometimes you run into an error message like this:

```
GraphQLError: Response not successful: Received status code 500
    at Object.locatedError (/Users/marcusboehm/R/github.com/graphcool/cloud-api/node_modules/graphql/error/locatedError.js:23:10)
    at Object.checkResultAndHandleErrors (/Users/marcusboehm/R/github.com/graphcool/cloud-api/node_modules/graphql-tools/src/stitching/errors.ts:83:11)
    at Object.<anonymous> (/Users/marcusboehm/R/github.com/graphcool/cloud-api/node_modules/graphql-tools/src/stitching/delegateToSchema.ts:91:14)
    at step (/Users/marcusboehm/R/github.com/graphcool/cloud-api/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:40:23)
    at Object.next (/Users/marcusboehm/R/github.com/graphcool/cloud-api/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:21:53)
    at fulfilled (/Users/marcusboehm/R/github.com/graphcool/cloud-api/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:12:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

There should be a flag to enable better logging:
* more information when an error occurs
* more information when mutations/queries run successfully
* ...

**Comment by schickling** [comment]
This should be much improved with the `new Graphcool({ debug: true })` option.
