### ISSUE TITLE
Better error message when delegating selection set for scalar fields

### ISSUE THREAD

**Issue by sorenbs** [graphcool/graphcool-binding#19]
Mutation:

```graphql
mutation {
  updatePassword(password: String!): String!
}}
```

resolver:

```js
ctx.db.mutation.updateLogin(
  {
    where: { id: loginId },
    data: { name: newName },
  },
  info
)
```

Results in this error:

```
GraphQLError: Field 'updateLogin' of type 'Login' must have a sub selection. (line 2, column 3):
  updateLogin(data: $_data, where: $_where)
  ^
    at Object.locatedError (/Users/sorenbs/code/gc/cloud/node_modules/graphql/error/locatedError.js:23:10)
    at Object.checkResultAndHandleErrors (/Users/sorenbs/code/gc/cloud/node_modules/graphql-tools/src/stitching/errors.ts:83:11)
    at Object.<anonymous> (/Users/sorenbs/code/gc/cloud/node_modules/graphql-tools/src/stitching/delegateToSchema.ts:91:14)
    at step (/Users/sorenbs/code/gc/cloud/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:40:23)
    at Object.next (/Users/sorenbs/code/gc/cloud/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:21:53)
    at fulfilled (/Users/sorenbs/code/gc/cloud/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:12:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

as there is no selection set in info. This makes sense, but can be confusing.

Could we provide a better error message?

**Comment by schickling** [comment]
This is fixed in the newest release.
