### ISSUE TITLE
Cannot read property 'getMutationType' of undefined

### ISSUE THREAD

**Issue by nikolasburk** [graphcool/graphcool-binding#25]
I'm trying to produce a simple auth example, you can find the full repo [here](https://github.com/nikolasburk/gc-migration-auth-example).

The project is setup as follows:

**index.js**

```js
const { GraphQLServer } = require('graphql-yoga')
const { importSchema } = require('graphql-import')
const { Graphcool } = require('graphcool-binding')
const { me, signup, login, AuthPayload } = require('./auth')

const typeDefs = importSchema('./src/schema.graphql')
console.log(typeDefs)

const resolvers = {
  Query: {
    me,
  },
  Mutation: {
    signup,
  //   login,
  },
}

const server = new GraphQLServer({
  typeDefs,
  resolvers,
  context: req => ({
    ...req,
    db: new Graphcool({
      schemaPath: './database/schema.generated.graphql',
      endpoint: process.env.GRAPHCOOL_ENDPOINT,
      secret: process.env.GRAPHCOOL_SECRET,
    }),
  }),
})

server.start(() => console.log('Server is running on http://localhost:4000'))
```

**schema.graphql**

```graphql
type Query {
  me: User
}

type Mutation {
  signup(email: String!, password: String!): AuthPayload!
  # login(email: String!, password: String!): AuthPayload!
}

type AuthPayload {
  token: String!
  user: User!
}

type User {
  id: ID!
  email: String!
  name: String!
}
```

**auth.js**

```js
const bcrypt = require('bcryptjs')
const jwt = require('jsonwebtoken')
const { Context, getUserId } = require('./utils')

const AuthPayload = {
  user: async ({ user: { id } }, args, ctx, info) => {
    return ctx.db.query.user({ where: { id } }, info)
  }
}

// query the currently logged in user
function me(parent, args, ctx, info) {
  const id = getUserId(ctx)
  return ctx.db.query.user({ where: { id } }, info)
}

// register a new user
async function signup(parent, args, ctx, info) {
  const password = await bcrypt.hash(args.password, 10)
  const user = await ctx.db.mutation.createUser({
    data: { ...args, password },
  })

  return {
    token: jwt.sign({ userId: user.id }, process.env.JWT_SECRET),
    user,
  }
}

// log in an existing user
async function login(parent, { email, password }, ctx, info) {
  const user = await ctx.db.query.user({ where: { email } })
  if (!user) {
    throw new Error(`No such user found for email: ${email}`)
  }

  const valid = await bcrypt.compare(password, user.password)
  if (!valid) {
    throw new Error('Invalid password')
  }

  return {
    token: jwt.sign({ userId: user.id }, process.env.JWT_SECRET),
    user,
  }
}

module.exports = { me, signup, login, AuthPayload }
```

**utils.js**

```js
const jwt = require('jsonwebtoken')
const { Graphcool } = require('graphcool-binding')

function getUserId(ctx) {
  const Authorization = ctx.request.get('Authorization')
  if (Authorization) {
    const token = Authorization.replace('Bearer ', '')
    const { userId } = jwt.verify(token, process.env.JWT_SECRET)
    return userId
  }

  throw new AuthError()
}

class AuthError extends Error {
  constructor() {
    super('Not authorized')
  }
}

module.exports = {
  getUserId,
  AuthError
}
```

I am getting an error when sending the `signup` mutation:

```graphql
mutation {
  signup(email:"asd@asd.com" password: "asd") {
    token
  }
}
```

This is the full error message:

```
TypeError: Cannot read property 'getMutationType' of undefined
    at Object.getTypeForRootFieldName (/Users/nburk/Projects/graphcool/docs/migration-example/1.0/myapp/node_modules/graphql-binding/dist/utils.js:25:45)
    at buildInfoForAllScalars (/Users/nburk/Projects/graphcool/docs/migration-example/1.0/myapp/node_modules/graphql-binding/dist/info.js:17:24)
    at Object.buildInfo (/Users/nburk/Projects/graphcool/docs/migration-example/1.0/myapp/node_modules/graphql-binding/dist/info.js:7:16)
    at Proxy.<anonymous> (/Users/nburk/Projects/graphcool/docs/migration-example/1.0/myapp/node_modules/graphql-binding/dist/handler.js:15:27)
    at signup (/Users/nburk/Projects/graphcool/docs/migration-example/1.0/myapp/src/auth.js:20:38)
    at <anonymous>
```

**Comment by schickling** [comment]
This should be fixed in `0.3.5`. Thanks for reporting!
