### ISSUE TITLE
Doesn't generate subscription type correctly

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool-binding#68]
Error message:

> Argument of type 'string | GraphQLResolveInfo' is not assignable to parameter of type '{ [key: string]: any; }'

Reproduction:

```
npm install -g graphql-cli
graphql create my-app -b https://github.com/graphql-boilerplates/typescript-graphql-server/tree/f2f0bf5c76c8fce7fd47a5654ae71e7851d25f6b/basic
cd my-app
yarn start
```

```
 ~/p/p/b/t-b  yarn start
yarn start v0.27.5
warning package.json: No license field
$ ts-node src/index.ts

/Users/marktani/projects/playground/boilerplates/t-b/node_modules/graphcool-cli-core/node_modules/ts-node/src/index.ts:307
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
src/generated/graphcool.ts (398,124): Argument of type 'string | GraphQLResolveInfo' is not assignable to parameter of type '{ [key: string]: any; }'.
  Type 'string' is not assignable to type '{ [key: string]: any; }'. (2345)
    at getOutput (/Users/marktani/projects/playground/boilerplates/t-b/node_modules/graphcool-cli-core/node_modules/ts-node/src/index.ts:307:15)
    at /Users/marktani/projects/playground/boilerplates/t-b/node_modules/graphcool-cli-core/node_modules/ts-node/src/index.ts:336:16
    at Object.compile (/Users/marktani/projects/playground/boilerplates/t-b/node_modules/graphcool-cli-core/node_modules/ts-node/src/index.ts:498:11)
    at Module.m._compile (/Users/marktani/projects/playground/boilerplates/t-b/node_modules/graphcool-cli-core/node_modules/ts-node/src/index.ts:392:43)
    at Module._extensions..js (module.js:584:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/marktani/projects/playground/boilerplates/t-b/node_modules/graphcool-cli-core/node_modules/t
s-node/src/index.ts:395:12)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/marktani/projects/playground/boilerplates/t-b/src/index.ts:2:1)
    at Module._compile (module.js:573:30)
    at Module.m._compile (/Users/marktani/projects/playground/boilerplates/t-b/node_modules/graphcool-cli-core/node_modules/ts-node/src/index.ts:392:23)
    at Module._extensions..js (module.js:584:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/marktani/projects/playground/boilerplates/t-b/node_modules/graphcool-cli-core/node_modules/t
s-node/src/index.ts:395:12)
error Command failed with exit code 1.
```

Removing this from `src/generated/graphcool.ts` (around line 398) makes the server work without any problems:

```diff
- subscription: Subscription = {
-   post: (args, infoOrQuery): Promise<AsyncIterator<PostSubscriptionPayload>> =>  super.delegateSubscription('post', args, {}, infoOrQuery),
-     user: (args, infoOrQuery): Promise<AsyncIterator<UserSubscriptionPayload>> => super.delegateSubscription('user', args, {}, infoOrQuery)
-  }
```

A similar, but different, error occurs for the boilerplate `typescript-advanced`:

```sh
graphql create my-app2 -b https://github.com/graphql-boilerplates/typescript-graphql-server/tree/f2f0bf5c76c8fce7fd47a5654ae71e7851d25f6b/advanced
```

**Comment by marktani** [comment]
Confirmed that [this upgrade from `1.3.3` to `1.3.5`](https://github.com/graphql-boilerplates/typescript-graphql-server/commit/4d5d76c524968247d3b9a20c6fb94f196ef12316) introduced the error message. I created a _temporary branch_ that reverts this specific commit, and all works as expected there:

```
graphql create test -b https://github.com/graphql-boilerplates/typescript-graphql-server/tree/temp/advanced
cd test
yarn start
# it works!
```

**Comment by marktani** [comment]
This happens with `graphql-cli@2.11.0`.

**Comment by marktani** [comment]
I pinned `graphcool-binding@1.3.3` for now.

**Comment by kbrandwijk** [comment]
Seems like the dependency for graphql-cli is not updated in the graphcool-cli, causing `prepare` to generate 'old' code.

**Comment by kbrandwijk** [comment]
Is this fixed in graphcool cli now @marktani?

**Comment by marktani** [comment]
Will be soon.

**Comment by iamclaytonray** [comment]
I'm having this issue with queries, mutations, and subscriptions. I have the latest of every dep installed. Any ideas?

**Comment by marktani** [comment]
Please create a new issue and provide a reproduction, @iamclaytonray. Thanks!

**Comment by iamclaytonray** [comment]
Sure
